<template>
  <div style="width: 100%;height: 100px;top: 0px">
    <el-cascader v-model="selectChart"
                 :options="options"
                 @change="handleChange">
    </el-cascader>
    <el-button @click="toConfig">更改</el-button>
  </div>
</template>

<script>
export default {
  name: 'config',
  data(){
    return {
      selectChart:['line','gh_data'],
      options:[{
        value:'line',
        label:'折线图',
        children:[{
          value:'zbchongzu',
          label:'资本充足率'
        }, {
          value:'corezbchongzu',
          label:'核心资本充足率'
        },{
          value:'corefirstzbchongzu',
          label:'核心一级资本充足率'
        },{
          value:'zichanprofit',
          label:'资产利润率'
        },{
          value:'baddaikuan',
          label:'不良贷款率'
        },{
          value:'badzichan',
          label:'不良资产率'
        },{
          value:'liudongbili',
          label:'流动性比例'
        },{
          value:'corefuzhai',
          label:'核心负债依存度'
        },{
          value:'rorwa',
          label:'风险加权资产收益率'
        }
        ]
        },
        {//仪表盘
        value:'gauge',
        label:'仪表盘',
        children:[{
          value:'zbchongzu',
          label:'资本充足率',
          children:[{
            value:'season1',
            label:'第一季度'
          },{
            value:'season2',
            label:'第二季度'
          }]
        }, {
          value:'corezbchongzu',
          label:'核心资本充足率',
          children:[{
            value:'season1',
            label:'第一季度'
          },{
            value:'season2',
            label:'第二季度'
          }]
        },{
          value:'corefirstzbchongzu',
          label:'核心一级资本充足率',
          children:[{
            value:'season1',
            label:'第一季度'
          },{
            value:'season2',
            label:'第二季度'
          }]
        },{
          value:'zichanprofit',
          label:'资产利润率',
          children:[{
            value:'season1',
            label:'第一季度'
          },{
            value:'season2',
            label:'第二季度'
          }]
        },{
          value:'baddaikuan',
          label:'不良贷款率',
          children:[{
            value:'season1',
            label:'第一季度'
          },{
            value:'season2',
            label:'第二季度'
          }]
        },{
          value:'badzichan',
          label:'不良资产率',
          children:[{
            value:'season1',
            label:'第一季度'
          },{
            value:'season2',
            label:'第二季度'
          }]
        },{
          value:'liudongbili',
          label:'流动性比例',
          children:[{
            value:'season1',
            label:'第一季度'
          },{
            value:'season2',
            label:'第二季度'
          }]
        },{
          value:'corefuzhai',
          label:'核心负债依存度',
          children:[{
            value:'season1',
            label:'第一季度'
          },{
            value:'season2',
            label:'第二季度'
          }]
        },{
          value:'rorwa',
          label:'风险加权资产收益率',
          children:[{
            value:'season1',
            label:'第一季度'
          },{
            value:'season2',
            label:'第二季度'
          }]
        }
        ]
      }],
      bankData:{
        zbchongzu:{
          season1:0.1,
          season2:0.2
        },
        corezbchongzu:{
          season1:0.3,
          season2:0.25
        },
        corefirstzbchongzu:{
          season1:0.4,
          season2:0.3
        },
        zichanprofit:{
          season1:0.22,
          season2:0.44
        },
        baddaikuan:{
          season1:0.5,
          season2:0.15
        },
        badzichan:{
          season1:0.44,
          season2:0.33
        },
        liudongbili:{
          season1:0.35,
          season2:0.45
        },
        corefuzhai:{
          season1:0.1,
          season2:0.2
        },
        rorwa:{
          season1:0.5,
          season2:0.8
        }
      },
      configData:{
        chartType:'',
        bankChart:[],
        gaugeChart:50,
      }

    }
  },
  methods:{
    handleChange(){
      if (this.selectChart[0] == 'line'){
        this.configData.chartType = this.selectChart[0]
        for (let i in this.bankData[this.selectChart[1]]){
          this.configData.bankChart.push(this.bankData[this.selectChart[1]][i])
        }
      }
      else if (this.selectChart[0] == 'gauge') {
        this.configData.chartType = this.selectChart[0]
        this.configData.gaugeChart = this.bankData[this.selectChart[1]][this.selectChart[2]]
      }
    },
    toConfig(){
      this.$store.commit('changeChart',this.configData)
      // this.bus.$emit("change-config",this.configData)
    }
  }
}
</script>

<style scoped>

</style>
